"""proposal flow redesign: comment/regen/reopen schema changes

Revision ID: 6321657872cf
Revises: c5a426a0970d
Create Date: 2026-09-08 18:28:59.478180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6321657872cf'
down_revision: Union[str, Sequence[str], None] = 'c5a426a0970d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_comments', 'section_key',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='proposal_app')
    op.add_column('proposals', sa.Column('retired_client_token', sa.UUID(), nullable=True), schema='proposal_app')
    op.add_column(
        'proposals',
        sa.Column('is_regenerating', sa.Boolean(), nullable=False, server_default=sa.false()),
        schema='proposal_app',
    )
    op.alter_column('section_history', 'change_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('manual_edit', 'regenerate', 'full_regenerate', name='section_change_type', native_enum=False),
               existing_nullable=False,
               schema='proposal_app')
    # ### end Alembic commands ###

    # Data migration (not autogenerated): "everyone can create a new
    # proposal" - can_create stays a real, admin-editable flag (so it
    # could still be revoked from a specific person later), but every
    # existing active account gets it granted now, matching the new
    # default for every future invite too (see admin_users.html).
    op.execute("UPDATE proposal_app.users SET can_create = true WHERE is_active = true")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section_history', 'change_type',
               existing_type=sa.Enum('manual_edit', 'regenerate', 'full_regenerate', name='section_change_type', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               schema='proposal_app')
    op.drop_column('proposals', 'is_regenerating', schema='proposal_app')
    op.drop_column('proposals', 'retired_client_token', schema='proposal_app')
    op.alter_column('approval_comments', 'section_key',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='proposal_app')
    # ### end Alembic commands ###
