"""reference file trash and description

Revision ID: 963263fce38a
Revises: 6321657872cf
Create Date: 2026-09-08 21:10:42.446861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963263fce38a'
down_revision: Union[str, Sequence[str], None] = '6321657872cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_files', sa.Column('description', sa.Text(), nullable=True), schema='proposal_app')
    op.add_column('reference_files', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True), schema='proposal_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_files', 'deleted_at', schema='proposal_app')
    op.drop_column('reference_files', 'description', schema='proposal_app')
    # ### end Alembic commands ###
