"""create initial schema in proposal_app

Revision ID: 971140e3f89b
Revises: 
Create Date: 2026-09-07 02:13:39.960215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '971140e3f89b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS proposal_app")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='proposal_app'
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('date_of_call', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_needs_summary', sa.Text(), nullable=False),
    sa.Column('project_scope', sa.Text(), nullable=False),
    sa.Column('goals_and_objectives', sa.Text(), nullable=False),
    sa.Column('recommended_services', sa.Text(), nullable=False),
    sa.Column('proposed_timeline', sa.Text(), nullable=False),
    sa.Column('estimated_pricing', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'changes_requested', 'approved', 'sent', name='proposal_status', native_enum=False), nullable=False),
    sa.Column('client_token', sa.UUID(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['proposal_app.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['proposal_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_token'),
    schema='proposal_app'
    )
    op.create_table('reference_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_library', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['proposal_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='proposal_app'
    )
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal_app.proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='proposal_app'
    )
    op.create_table('approval_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['proposal_app.users.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal_app.proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='proposal_app'
    )
    op.create_table('delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='delivery_status', native_enum=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal_app.proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='proposal_app'
    )
    op.create_table('proposal_references',
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('reference_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal_app.proposals.id'], ),
    sa.ForeignKeyConstraint(['reference_file_id'], ['proposal_app.reference_files.id'], ),
    sa.PrimaryKeyConstraint('proposal_id', 'reference_file_id'),
    schema='proposal_app'
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('has_gap_marker', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal_app.proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='proposal_app'
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('full_content_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal_app.proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='proposal_app'
    )
    op.create_table('section_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('old_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=False),
    sa.Column('change_type', sa.Enum('manual_edit', 'regenerate', name='section_change_type', native_enum=False), nullable=False),
    sa.Column('triggering_comment', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['proposal_app.users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['proposal_app.sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='proposal_app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section_history', schema='proposal_app')
    op.drop_table('snapshots', schema='proposal_app')
    op.drop_table('sections', schema='proposal_app')
    op.drop_table('proposal_references', schema='proposal_app')
    op.drop_table('delivery_logs', schema='proposal_app')
    op.drop_table('approval_comments', schema='proposal_app')
    op.drop_table('access_logs', schema='proposal_app')
    op.drop_table('reference_files', schema='proposal_app')
    op.drop_table('proposals', schema='proposal_app')
    op.drop_table('users', schema='proposal_app')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS proposal_app")
