"""add account tokens, make password_hash nullable

Revision ID: c5a426a0970d
Revises: 971140e3f89b
Create Date: 2026-09-08 15:27:13.552191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a426a0970d'
down_revision: Union[str, Sequence[str], None] = '971140e3f89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('invite', 'reset', name='account_token_purpose', native_enum=False), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['proposal_app.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='proposal_app'
    )
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='proposal_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='proposal_app')
    op.drop_table('account_tokens', schema='proposal_app')
    # ### end Alembic commands ###
